build_from:
  aarch64: docker.io/joshava/cloudflare-ddns:2.9
  amd64: docker.io/joshava/cloudflare-ddns:2.9
  armhf: docker.io/joshava/cloudflare-ddns:2.9
  armv7: docker.io/joshava/cloudflare-ddns:2.9
args:
  BASHIO_VERSION: 0.16.2
  S6_OVERLAY_VERSION: 3.1.6.2