build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18
  armhf: ghcr.io/home-assistant/armhf-base-python:3.11-alpine3.18
  armv7: ghcr.io/home-assistant/armv7-base-python:3.11-alpine3.18
  i386: ghcr.io/home-assistant/i386-base-python:3.11-alpine3.18
args:
  CRYPTOGRAPHY_VERSION: 41.0.5
  CERTBOT_DNS_GODADDY_VERSION: 2.8.0
  CERTBOT_VERSION: 2.7.4
  ACME_VERSION: 2.7.4