---
version: 0.1.1
slug: letsencrypt_godaddy
name: Certbot SSL Manager (GoDaddy)
description: Manage certificate from GoDaddy using Certbot
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: manual
init: false
map:
  - ssl:rw
  - share
options:
  domains:
    - null
  email: null
  keytype: ecdsa
  keyfile: privkey.pem
  certfile: fullchain.pem
  challenge: http
  dns: {}
ports:
  80/tcp: 80
schema:
  domains:
    - str
  email: email
  keytype: list(ecdsa|rsa)?
  keyfile: str
  certfile: str
  challenge: list(dns|http)
  acme_root_ca_cert: str?
  acme_server: url?
  dns:
    godaddy_api_key: str?
    godaddy_api_secret: password?
    propagation_seconds: int(60,3600)?
    provider: "list(dns-godaddy)?"
    rfc2136_algorithm: str?
    rfc2136_name: str?
    rfc2136_port: str?
    rfc2136_secret: str?
    rfc2136_server: str?
startup: once